name: Sync SOPs to Wiki via APP

description: |
  This workflow syncs SOPs from the main repository to the wiki using a GitHub App token.
  It runs daily at 3 AM UTC and can also be triggered manually.
  The workflow uses the `tibdex/github-app-token` action to generate a token for the GitHub App,
  which is then used to clone the wiki repository and push changes.
  The `rsync` command is used to synchronize the SOPs directory with the wiki.

on:
  schedule:
    - cron: '0 3 * * *' # every day at 3 AM UTC
  workflow_dispatch: # also allows manual triggering
  
jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          installation_id: ${{ secrets.INSTALLATION_ID }}

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Remove existing wiki directory
        run: |
          if [ -d wiki ]; then rm -rf wiki; fi

      - name: Clone Wiki
        run: |
          git config --global user.name "Documentation Goblin"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone https://x-access-token:${{ steps.generate_token.outputs.token }}@github.com/${{ github.repository }}.wiki.git wiki

      - name: Sync and Push
        run: |
          mkdir -p wiki/SOPs
          rsync -av --delete SOPs/ wiki/SOPs/
          cd wiki
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "GitHub App: Update SOPs"
            git push
          fi
